### ISSUE TITLE
Make sure to format SQL according to best practices

### ISSUE THREAD

**Issue by jmcrey** [mlschutte/CodeAcademySQL#1]
Each of the SQL queries in the presentation and the separate SQL file accurately retrieve the data needed to answer the questions for this project. However, the queries are not the easiest to read because they do not utilize SQL's best practices for styling. For example, the funnel query is excellently crafted to grab the exact data we need; but, it does not capitalize key words or use indentation for easier reading. 

```
select distinct q.user_id,
h.user_id is not null as 'is_home_try_on',
h.number_of_pairs,
p.user_id is not null as 'is_purchase'
from quiz q
left join home_try_on h
on q.user_id = h.user_id
left join purchase p
on p.user_id = q.user_id
limit 10;
```

Above is the unformatted version of the funnel query. Now, utilizing the rules found on our [SQL Style Guide](https://s3.amazonaws.com/codecademy-content/programs/learn-sql-from-scratch/SQL+Style+Guide+for+Learn+SQL+from+Scratch.pdf), let's try to format this query. 

```
SELECT DISTINCT q.user_id,
       h.user_id IS NOT NULL AS 'is_home_try_on',
       h.number_of_pairs,
       p.user_id IS NOT NULL AS 'is_purchase'
FROM quiz q
LEFT JOIN home_try_on h
     ON q.user_id = h.user_id
LEFT JOIN purchase p
     ON p.user_id = q.user_id
LIMIT 10;
```

I did two things to accomplish this change: I capitalized each of the key words (e.g. `SELECT`, `DISTINCT`, `LEFT JOIN`, etc.) and I used indentation to give a visual separation to those queries with multiple lines/parts (e.g. on `LEFT JOIN` or `SELECT`). Using these two techniques, I was able to format the query such that it was easily read and understood by anyone who could read it. 

Although it seems like a small change, the stylizing rules help format the query for easy reading and/or for separation of functionality. For example, looking at this query, we know that each capital word is an action taken on the data while the lower case words are the data themselves. Further, the indentation allows the reader to more easily understand which parts of the query are relevant to each other.

Besides stylizing, however, these queries are perfect! Great job!

**Comment by mlschutte** [comment]
Noted. Much thanks!
